[project]
name = "comfyui-lora-manager"
description = "LoRA Manager for ComfyUI - An extension for managing LoRA models with previews and metadata integration."
version = "0.5.1"
license = {file = "LICENSE"}
dependencies = ["aiohttp", "jinja2", "safetensors"]

[project.urls]
Repository = "https://github.com/willmiao/ComfyUI-Lora-Manager"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "willmiao"
DisplayName = "ComfyUI-Lora-Manager"
Icon = ""
